SilverStripe\Core\Injector\Injector:
  RedirectsCache:
    class: Doctrine\Common\Cache\FilesystemCache
    constructor:
      0: '../silverstripe-redirects/cache'

  RedirectUrlDataSource:
    class: Heyday\SilverStripeRedirects\Source\DataSource\DataListDataSource
    constructor:
      0: %$RedirectUrlDataList
      1: %$Heyday\SilverStripeRedirects\Source\Transformer\RedirectUrlTransformer

  CachedRedirectUrlDataSource:
    class: Heyday\SilverStripeRedirects\Source\DataSource\CachedDataSource
    constructor:
      0: %$RedirectUrlDataSource
      1: %$RedirectsCache

  Heyday\SilverStripeRedirects\Code\RedirectUrl:
    properties:
      dataSource: %$CachedRedirectUrlDataSource

  RedirectUrlDataList:
    class: SilverStripe\ORM\DataList
    constructor:
      0: 'Heyday\SilverStripeRedirects\Code\RedirectUrl'

  Heyday\SilverStripeRedirects\Source\Redirector:
    constructor:
      0: %$CachedRedirectUrlDataSource

  Heyday\SilverStripeRedirects\Source\RequestFilter:
    constructor:
      0: %$Heyday\SilverStripeRedirects\Source\Redirector

  SilverStripe\Control\RequestProcessor:
    properties:
      filters:
        - '%$Heyday\SilverStripeRedirects\Source\RequestFilter'