---
Name: redirects
---
SilverStripe\Core\Injector\Injector:
  RedirectUrlDataSource:
    class: Heyday\SilverStripeRedirects\Source\DataSource\DataListDataSource
    constructor:
      0: '%$RedirectUrlDataList'
      1: '%$Heyday\SilverStripeRedirects\Source\Transformer\RedirectUrlTransformer'

  CachedRedirectUrlDataSource:
    class: Heyday\SilverStripeRedirects\Source\DataSource\CachedDataSource
    constructor:
      0: '%$RedirectUrlDataSource'

  Heyday\SilverStripeRedirects\Source\RedirectUrl:
    properties:
      dataSource: '%$CachedRedirectUrlDataSource'

  RedirectUrlDataList:
    class: SilverStripe\ORM\DataList
    constructor:
      0: 'Heyday\SilverStripeRedirects\Source\RedirectUrl'

  Heyday\SilverStripeRedirects\Source\Redirector:
    constructor:
      0: '%$CachedRedirectUrlDataSource'

  Heyday\SilverStripeRedirects\Source\RequestFilter:
    constructor:
      0: '%$Heyday\SilverStripeRedirects\Source\Redirector'

  Psr\SimpleCache\CacheInterface.redirectsCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "redirectsCache"
---
Name: redirects-processing
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        RedirectMiddleware: '%$Heyday\SilverStripeRedirects\Source\RequestFilter'
